---
title: "Midterm Project 1"
author: "Thomas Raines"
date: "9/29/2021"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r}

library("dplyr")


library("ggplot2")


library("lubridate")


library("reshape2")


library("stringi")
```



```{r}
#Set our Working Directory
getwd()
setwd("C:/Users/Proje/OneDrive/Desktop/Data Analytics Projects/Midterm Part One/COVID-19-master")

```



```{r}
## Create our dataframe for the cases time-series
time_series_df = data.frame(read.csv("C:/Users/Proje/OneDrive/Desktop/Data Analytics Projects/Midterm Part One/COVID-19-master/COVID-19-master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"))

##Print our DF
time_series_df


##Get the Structure of DF1
str(time_series_df)

```

```{r}
##Make Dataframe 2 (Google Mobility data)


google_mobility_df = data.frame(read.csv("C:/Users/Proje/OneDrive/Desktop/Data Analytics Projects/Midterm Part One/COVID-19-master/COVID-19-master/csse_covid_19_data/csse_covid_19_time_series/googlemobility.csv"))

##Print df 2
head(google_mobility_df)

##Get structure of DF2
str(google_mobility_df)



```



```{r}
## Sort time series to only have fields of "United Kingdom"

uk_time_series = filter(time_series_df, `Country.Region` == "United Kingdom")

##Print the new Time series
head(uk_time_series)


##Problem here, the date formats have X's In them, so we need to fix that

```



```{r}
##Make duplicate DF
uk_time_series_new = uk_time_series
##remove X from dates (replace every X with a "")
colnames(uk_time_series_new) <- gsub("X", "", colnames(uk_time_series_new))

##Print uk_time_series_new
head(uk_time_series_new)

```


```{r}

##Since the new df looks good, but it needs the "."s removed

##make duplicate time series to manipulate
ukts1 = uk_time_series_new


##replace every period ("\\." with a hyphen "-")
colnames(ukts1) = gsub("\\.", "-", colnames(ukts1))

##Print ukts1
head(ukts1)



```




```{r}

## take a subset and remove every column that's not a date

ukts_Dates_Only = subset(ukts1, select = -c(1, 2 ,3, 4))

##Summarize each regions data into one column

ukts_Dates_Only <- ukts_Dates_Only %>% summarise(across(everything(), sum, na.rm = TRUE))

##print
head(ukts_Dates_Only)

```



```{r}
##Transpose our Dataframe
ukts_Dates_Only_new = data.frame(t(ukts_Dates_Only))
str(ukts_Dates_Only_new)


##Make a column called date and put our row names into it
ukts_Dates_Only_new$date <- mdy(row.names(ukts_Dates_Only_new))


ukts_Dates_Only_new$t.ukts_Dates_Only. = c(0, diff(as.numeric(ukts_Dates_Only_new$t.ukts_Dates_Only.)))

##Print
head(ukts_Dates_Only_new)


```




```{r}
## Google Mobility data to only have fields of "United Kingdom"
uk_mobility = filter(google_mobility_df, `country_region` == "United Kingdom")

#Print
head(uk_mobility)

```

```{r}

##Remove columns that we don't need
uk_mobility_date_and_data_only = subset(uk_mobility, select = -c(1, 2 ,3, 4, 5, 6, 7, 8))


##Print
head(uk_mobility_date_and_data_only)



##change date column to date type
uk_mobility_date_and_data_only$date = as.Date(uk_mobility_date_and_data_only$date)


##Structure of refined mobility
str(uk_mobility_date_and_data_only)


##Sumarize everything by date
uk_mobility_date_and_data_only <- uk_mobility_date_and_data_only %>% group_by(date) %>% summarise(across(everything(), mean, na.rm = TRUE))


##MAKE copy of df
ukMo = uk_mobility_date_and_data_only





##Print
data.frame(uk_mobility_date_and_data_only)



```




```{r}

## We need to merge our new Dataframes
merged_df = merge(ukts_Dates_Only_new, ukMo , group_by = date)

names(merged_df)[2] = "Case Count"

row.names(  merged_df ) =  merged_df$date
head(merged_df)

names(merged_df)

##Select Columns, normalize and overlay

merged_df2  <- merged_df  %>% dplyr::select(2:8 )

merged_df_scaled <-  data.frame( scale(merged_df2) )
head( merged_df_scaled )

# add the date column back
merged_df_scaled$date = ymd(row.names(merged_df_scaled))
tail( merged_df_scaled )









```

```{r}

selected_columns = c('Case.Count' , 'retail_and_recreation_percent_change_from_baseline', 'grocery_and_pharmacy_percent_change_from_baseline' , 'parks_percent_change_from_baseline', 'transit_stations_percent_change_from_baseline', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline' )

##Time to melt our Data Frames
melted_df = melt(merged_df_scaled, measure.vars = selected_columns, value.names = "Values", variable.name = "variable")


head(melted_df)


```

```{r}


myplot = ggplot(melted_df, aes(x = `date` , y = `value`, color = `variable` ))+
  stat_smooth(span=0.15, se=FALSE)
  
  

  
 

##Print our plot
head(myplot)

myplot
```
